#!/bin/sh -uxe

./config --prefix=/usr --openssldir=/etc/ssl --libdir=lib shared zlib-dynamic linux-x86_64 enable-ec_nistp_64_gcc_128
make
make DESTDIR="$1" MANDIR=/usr/share/man MANSUFFIX=ssl install
