#!/bin/sh -uxe

sed 's/\(curl_LDADD =\)/\1 -all-static/' src/Makefile.in > _
mv -f _ src/Makefile.in

./configure --prefix=/usr --enable-ipv6 --enable-unix-sockets --enable-hidden-symbold --disable-manual \
            --disable-ldap --enable-ares --with-openssl --with-pic --with-ca-fallback --without-librtmp \
            --without-icu --without-libpsl --without-libidn --without-libidn2 --without-zstd
make
make install
