#!/bin/sh -uxe

./configure --prefix=/usr --syslibdir=/usr/lib
make
make install

mkdir -p "$1/usr/bin"
ln -s /usr/lib/ld-musl-x86_64.so.1 "$1/usr/bin/ldd"

ln -sf libc.so "$1/usr/lib/ld-musl-x86_64.so.1"

cp -f cdefs.h queue.h tree.h "$1/usr/include/sys"
cc getconf.c -o "$1/usr/bin/getconf"
cc getent.c -o "$1/usr/bin/getent"
